# Generated by Django 3.1.4 on 2021-04-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='context',
            new_name='content',
        ),
    ]
